# Generated by Django 5.1.6 on 2025-03-09 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('uzmanlik_alani', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_numarasi', models.CharField(max_length=20, unique=True)),
                ('pdf_dosya', models.FileField(upload_to='makaleler/')),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Değerlendirmede', 'Değerlendirmede'), ('Kabul Edildi', 'Kabul Edildi'), ('Reddedildi', 'Reddedildi')], default='Beklemede', max_length=50)),
                ('anonimlestirildi_mi', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makaleler', to='makale_sistemi.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField()),
                ('yorum', models.TextField()),
                ('degerlendirme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('hakem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='makale_sistemi.hakem')),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='makale_sistemi.makale')),
            ],
        ),
        migrations.CreateModel(
            name='AnonimleştirmeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yapilan_islem', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonimlestirme_loglari', to=settings.AUTH_USER_MODEL)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonimlestirme_loglari', to='makale_sistemi.makale')),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('gonderim_tarihi', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to='makale_sistemi.kullanici')),
            ],
        ),
    ]
