# Generated by Django 5.1.6 on 2025-03-09 10:44

import makale_sistemi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='takip_numarasi',
            field=models.CharField(default=makale_sistemi.models.takip_numarasi_olustur, max_length=20, unique=True),
        ),
    ]
