# Generated by Django 5.1.6 on 2025-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0002_alter_makale_takip_numarasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='anonim_pdf_dosya',
            field=models.FileField(blank=True, null=True, upload_to='anonim_makaleler/'),
        ),
    ]
