# Generated by Django 5.1.6 on 2025-03-19 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0003_makale_anonim_pdf_dosya'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='alici',
        ),
        migrations.RemoveField(
            model_name='mesaj',
            name='gonderen',
        ),
        migrations.AddField(
            model_name='mesaj',
            name='alici_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_alinan_mesajlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesaj',
            name='alici_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alinan_mesajlar', to='makale_sistemi.kullanici'),
        ),
        migrations.AddField(
            model_name='mesaj',
            name='gonderen_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_gonderilen_mesajlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesaj',
            name='gonderen_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to='makale_sistemi.kullanici'),
        ),
    ]
