# Generated by Django 5.1.6 on 2025-03-22 11:14

import django.db.models.deletion
import makale_sistemi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0004_remove_mesaj_alici_remove_mesaj_gonderen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='hakem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atanan_makaleler', to='makale_sistemi.hakem'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='anonim_pdf_dosya',
            field=models.FileField(upload_to=makale_sistemi.models.anonim_dosya_yolu),
        ),
        migrations.AlterField(
            model_name='makale',
            name='pdf_dosya',
            field=models.FileField(upload_to=makale_sistemi.models.makale_dosya_yolu),
        ),
    ]
