# Generated by Django 5.1.6 on 2025-03-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0005_makale_hakem_alter_makale_anonim_pdf_dosya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degerlendirme',
            name='puan',
        ),
    ]
