# Generated by Django 5.1.6 on 2025-03-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0006_remove_degerlendirme_puan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonimEtiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('encrypted', models.TextField()),
                ('category', models.CharField(choices=[('ISIM', 'Yazar Adı'), ('EMAIL', 'Email'), ('KURUM', 'Kurum')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
