# Generated by Django 5.1.6 on 2025-03-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0007_anonimetiket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonimetiket',
            name='category',
            field=models.CharField(choices=[('ISIM', 'Yazar Adi'), ('EMAIL', 'Email'), ('KURUM', 'Kurum')], max_length=20),
        ),
    ]
