# Generated by Django 5.1.6 on 2025-03-31 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0008_alter_anonimetiket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonimetiket',
            name='makale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonim_etiketleri', to='makale_sistemi.makale'),
        ),
    ]
