# Generated by Django 5.1.6 on 2025-03-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0009_anonimetiket_makale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonimetiket',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='anonimetiket',
            unique_together={('makale', 'tag')},
        ),
    ]
