# Generated by Django 5.1.6 on 2025-03-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0010_alter_anonimetiket_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='durum',
            field=models.CharField(choices=[('Değerlendirmede', 'Değerlendirmede'), ('Kabul Edildi', 'Kabul Edildi'), ('Reddedildi', 'Reddedildi')], default='Değerlendirmede', max_length=50),
        ),
    ]
