# Generated by Django 5.1.6 on 2025-03-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale_sistemi', '0011_alter_makale_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='durum',
            field=models.CharField(choices=[('Beklemede', 'Beklemede'), ('Değerlendirmede', 'Değerlendirmede'), ('Kabul Edildi', 'Kabul Edildi'), ('Reddedildi', 'Reddedildi')], default='Beklemede', max_length=50),
        ),
    ]
